### ISSUE TITLE
Decide when to start a session (maybe for start_create)

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#267]
https://github.com/MoveOnOrg/mop-frontend/blob/master/src/actions/sessionActions.js#L63
currently only hits the session json api when there's already a cookie or if there's an akid token etc.

This currently differs from production setup because all visits start a session (though in practice, we don't start a session on the petition page until they sign (because of the CDN).

We may want to relax this a little -- e.g. start a session when someone starts to create a petition (so we can save intermediate products like the production version does).

**Comment by sreynen** [comment]
I think we settled this in chat after this issue was created. I believe the plan is to save intermediate state only on the client and only send the complete petition to the server. So we don't need anonymous session for this. We do need to create an account and login session when the petition is submitted, but that will be on the server side, so closing this.
