### ISSUE TITLE
Update signPetition() action to submit signatures to API

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#30]
Note: API for this doesn't yet exist, but let's assume for now it's a POST request to `petitions/${petitionSlug}/signatures`

**Comment by schuyler1d** [comment]
This commit POSTs to the current api 4430a875
(not the api path in the issue (`petitions/:slug/signatures`), which I don't think we should do, since we need an independent route which can go directly to the SQS queue (rather than elegantly be part of a predictable RESTful api -- but I think it's worth it)
