### ISSUE TITLE
Replace or polyfill Object.assign calls

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#358]
Turns out IE (pre-Edge) doesn't support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign and there's still a lot of people using IE. These people see a blank screen with a console error on Object.assign.

**Comment by jparkrr** [comment]
I think we should use https://babeljs.io/docs/plugins/preset-env/, be which automatically pollyfills for the browsers you want to support, because there's probably more things we need to pollyfill, like `fetch` and promises.

Their defaults are a pretty good start http://browserl.ist/?q=%3E0.5%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead, but let me know how I should configure this.

**Comment by jparkrr** [comment]
I used https://github.com/amilajack/eslint-plugin-compat to try to check which features we need polyfills for, and it's only returning fetch (which we already have in `whatwg-fetch`) and Promise, used in https://github.com/MoveOnOrg/mop-frontend/blob/fix-thanks-next-message-interval/src/loaders/petition.js

So I'm not sure if adding all of the polyfills is overkill or not (but there could be other things it's missing: Object.assign isn't flagged for some reasons)

**Comment by jparkrr** [comment]
I was testing it and setting babel-preset-env with those settings seemed to add a lot of weight to the bundle, but I could of been doing something wrong.

So I decided to just import the polyfills directly and confirm that it works on ie 11.
