### ISSUE TITLE
Add petition creation form component, add to petition create page

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#55]
For deployment this will be blocked on: https://github.com/MoveOnOrg/mop/issues/23
however, part of this should be to create a set of file(s) in `./local/api/v1/targets/{group}.json` which can be used for testing.  You can assume the output of target_search.html but you can also require additional (useful?) fields that the backend can use.

**Comment by sreynen** [comment]
I think all the basic form and dynamic instructions is working in https://github.com/MoveOnOrg/mop-frontend/tree/55-create-petition

What I see that's left to do:

- [ ] nav should be hidden on this page
- [ ] target search
- [ ] form validation
- [ ] submit

Going to focus on other things for a bit. Anyone else is welcome to pick this up.

**Comment by shakalee14** [comment]
This will be broken out into separate issues (because it will get big) and we will make a PR out of this branch: https://github.com/MoveOnOrg/mop-frontend/tree/55-create-petition 

**Nav should be hidden on this page**
- have the nav display handled with redux - we usually hide the nav when we don't want it to distract from the action featured on the page

**Target Search**
- sample api url: https://broom.moveon.org/api/legacy/target_search.html?search=char&group=senatemem
- recreate autocomplete interface

 **Form Validation and Submit**
- follow logic for signature form validation
- submit --> can submit 'anywhere' since api has not been created
